language: python
python:
  - 3.5
  - 3.6
  - pypy3
services:
    - elasticsearch
cache: pip
install:
  - pip install -r tools/requirements-devel.txt 
script:
  - make test
  - make test-backend-es-qs
