language: python
python:
  - 3.6
cache: pip
install:
  - pip install pyyaml
  - pip install yamllint

script:
  - yamllint .
  - tools/sigmac.py -rvdI -t es-qs rules/ 
  - tools/sigmac.py -rvdI -t splunk rules/ 
  - tools/sigmac.py -rvdI -t logpoint rules/ 
  - tools/sigmac.py -rvdI -t fieldlist rules/ 
