logsources:
  windows-security:
    product: windows
    service: security
    conditions:
      event_source: 'Microsoft-Windows-Security-Auditing'
  windows-security:
    product: windows
    service: system
    conditions:
      event_source: 'Microsoft-Windows-Security-Auditing'
fieldmappings:
    EventID: event_id
    FailureCode: result_code
    GroupName: group_name
    ServiceName: service
    SubjectAccountName: target_user
    TicketOptions: ticket_options
    TicketEnctyption: ticket_encryption
    Type: event_type
