title: DNS Server Error Failed Loading the ServerLevelPluginDLL
description: This rule detects a DNS server error in which a specified plugin DLL (in registry) could not be loaded
status: experimental
date: 2017/05/08
reference: 
    - https://medium.com/@esnesenon/feature-not-bug-dnsadmin-to-dc-compromise-in-one-line-a0f779b8dc83
    - https://technet.microsoft.com/en-us/library/cc735829(v=ws.10).aspx
author: Florian Roth
logsource:
    product: windows
    service: dns-server
detection:
    selection:
        EventID: 150
    condition: selection
falsepositives: 
    - Unknown
level: critical

